# Generated by Django 5.2.8 on 2025-12-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('library', '0004_savedgame_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.review'),
        ),
        migrations.AddField(
            model_name='activity',
            name='shelf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('play', 'Started Playing'), ('complete', 'Completed Game'), ('review', 'Left a Review'), ('add', 'Added to Library'), ('status', 'Updated Status')], max_length=20),
        ),
    ]
